---
- name: new web server
  hosts: myansibleclient
  
  tasks:
    - name: Package installation
      yum: name=httpd state=present
      
    - name: Amending webserver configuration file
      copy: path=/var/www/html/index.html content="This my first github file"
      
    - name: Starting webserver services
      service: name=httpd state=started
...